
chapter=[];//这里面全是对象，每隔对象是一关的各类东西位置
	chapter.push(temp1);
	chapter.push(temp2);
	chapter.push(temp3);
	chapter.push(temp4);
	chapter.push(temp5);
	chapter.push(temp6);
	chapter.push(temp7);
	chapter.push(temp8);
	chapter.push(temp9);
	chapter.push(temp10);
	chapter.push(temp11);
	chapter.push(temp12);
	chapter.push(temp13);
	chapter.push(temp14);
	chapter.push(temp15);
	chapter.push(temp16);
	chapter.push(temp17);
	chapter.push(temp18);
	chapter.push(temp19);
	chapter.push(temp20);
	chapter.push(temp21);
	chapter.push(temp22);
	chapter.push(temp23);
	chapter.push(temp24);
	chapter.push(temp25);
	chapter.push(temp26);
	chapter.push(temp27);
	chapter.push(temp28);
	chapter.push(temp29);
	chapter.push(temp30);
	one=$$("one"),two=$$("two"),three=$$("three"),four=$$("four"),
	five=$$("five"),six=$$("six"),seven=$$("seven"),eight=$$("eight"),nine=$$("nine"),
	ten=$$("ten"),t11=$$("eleven"),t12=$$("twelve"),t13=$$("thirteen"),
	t14=$$("fourteen"),t15=$$("fifteen"),t16=$$("sixteen"),t17=$$("seventeen"),
	t18=$$("eighteen"),t19=$$("nineteen"),t20=$$("twenty"),t21=$$("t21");
	t22=$$("t22"),t23=$$("t23"),t24=$$("t24"),t25=$$("t25"),t26=$$("t26"),
	t27=$$("t27"),t28=$$("t28"),t29=$$("t29"),t30=$$("t30");

	one.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=0;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//算是跟新数组吧，防止一关重复时子弹速度倍增
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	two.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=1;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	three.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=2;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	four.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=3;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	five.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=4;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//算是跟新数组吧，防止一关重复时子弹速度倍增
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	six.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=5;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();play_chapter_music();
	}
	seven.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=6;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();play_chapter_music();
	}
	eight.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=7;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//算是跟新数组吧，防止一关重复时子弹速度倍增
		if(!BEGIN_GAME)return;
		 play_chapter_music();play_chapter_music();
	}
	nine.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=8;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();play_chapter_music();
	}
	ten.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=9;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();play_chapter_music();
	}
	eleven.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=10;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//算是跟新数组吧，防止一关重复时子弹速度倍增
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	twelve.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=11;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	thirteen.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=12;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	fourteen.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=13;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//算是跟新数组吧，防止一关重复时子弹速度倍增
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	fifteen.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=14;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	sixteen.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=15;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	seventeen.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=16;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//算是跟新数组吧，防止一关重复时子弹速度倍增
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	eighteen.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=17;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	nineteen.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=18;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	twenty.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=19;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//算是跟新数组吧，防止一关重复时子弹速度倍增
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t21.onclick=function(){
		wall_color=2;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=20;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t22.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=21;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t23.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=22;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t24.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=23;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t25.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=24;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t26.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=25;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t27.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=26;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t28.onclick=function(){
		wall_color=1;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=27;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t29.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=28;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}
	t30.onclick=function(){
		wall_color=0;
		flag=0,flag2=0;alpha=0;
		CHAPTER_NUM=29;BEGIN_GAME=true;
		beginGame(chapter);
		bullet={};//同上
		if(!BEGIN_GAME)return;
		 play_chapter_music();
	}

	//怎么停止function--傻了，用return play_chapter_music();就行
	